dart-lang/leak_tracker

- .github/dependabot.yaml
- .github/workflows/dart.yaml
- .gitignore
- AUTHORS
- CONTRIBUTING.md
- various updates from the dart-lang template repo (https://github.com/dart-lang/dartlang_project_templates)
cc @polina-c
> updates from the dart-lang template repo

- lib/leak_analysis.dart
- lib/leak_tracker.dart
- lib/src/_util.dart
- lib/src/model.dart
- pubspec.yaml
- test/_util_test.dart
- test/model_test.dart
The model code is copied from [devtools](https://github.com/flutter/devtools/tree/master/packages/devtools_app/lib/src/screens/memory/panes/leaks/instrumentation) in order to be cleared from devtools by referencing leak_tracker.
> Copy model from devtools to leak_tracker.

- CODEOWNERS
> adding myself as codeowner

- CHANGELOG.md
- analysis_options.yaml
- example/main.dart
- example/pubspec.yaml
- lib/src/_leak_checker.dart
- lib/src/_object_record.dart
- lib/src/_object_tracker.dart
- lib/src/_util.dart
- lib/src/devtools_integration/_protocol.dart
- lib/src/devtools_integration/_registration.dart
- lib/src/leak_tracker.dart
- lib/src/leak_tracker_model.dart
- lib/src/orchestration.dart
- lib/src/shared_model.dart
- pubspec.yaml
- test/dart/_leak_checker_test.dart
- test/dart/_object_tracker_test.dart
- test/dart/devtools_integration/delivery_test.dart
Test config is needed to address the comment: https://github.com/flutter/flutter/pull/124435#discussion_r1169056964
> Test config and flutter lints.

- .gitignore
- CHANGELOG.md
- lib/src/leak_tracking/_object_tracker.dart
- lib/src/shared/_primitives.dart
- test/dart/leak_tracking/_object_tracker_test.dart
Contributes towards https://github.com/flutter/flutter/issues/126259
> Make sure leak tracker does not fail in case of duplicates.

- pkgs/leak_tracker/lib/src/leak_tracking/leak_tracker.dart
- pkgs/leak_tracker/lib/src/leak_tracking/leak_tracker_model.dart
- pkgs/leak_tracker/test/release/leak_tracking/_leak_checker_test.dart
small change about LeakTrackingConfiguration to be const.
---
<details>
Note that many …
> make LeakTrackingConfiguration to const

- pkgs/leak_tracker/analysis_options.yaml
Issue reference: https://github.com/dart-lang/sdk/issues/50679
> Remove mentions to deprecated strong_mode options

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/lib/src/leak_tracking/_baseliner.dart
- pkgs/leak_tracker/lib/src/leak_tracking/_leak_filter.dart
- pkgs/leak_tracker/lib/src/leak_tracking/_leak_tracker.dart
- pkgs/leak_tracker/lib/src/leak_tracking/_object_tracker.dart
- pkgs/leak_tracker/lib/src/leak_tracking/_primitives/model.dart
- pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart
- pkgs/leak_tracker/pubspec.yaml
- pkgs/leak_tracker/test/test_infra/mocks/mock_object_tracker.dart
- pkgs/leak_tracker/test/tests/leak_tracking/_leak_filter_test.dart
- pkgs/leak_tracker/test/tests/leak_tracking/_object_tracker_test.dart
- pkgs/leak_tracker/test/tests/leak_tracking/end_to_end_test.dart
- pkgs/leak_tracker/test/tests/leak_tracking/model_test.dart
- pkgs/leak_tracker_flutter_testing/CHANGELOG.md
- pkgs/leak_tracker_flutter_testing/lib/src/leak_testing.dart
- pkgs/leak_tracker_flutter_testing/lib/src/model.dart
- pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart
- pkgs/leak_tracker_flutter_testing/pubspec.yaml
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/baselining_test.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/failing_tests/failure_test.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/failing_tests/flutter_test_config.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/no_config_test.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/per_test_config_test/flutter_test_config.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/per_test_config_test/per_test_config_test.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/settings_not_disposed_off_test/flutter_test_config.dart
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/settings_not_gced_off_test/flutter_test_config.dart
- pkgs/leak_tracker_flutter_testing/test/tests/leak_testing_test.dart
Contributes to https://github.com/flutter/flutter/issues/135856
> Update leak_tracker to use LeakTesting.

- pkgs/leak_tracker/lib/src/shared/_util.dart
This PR fixes typo in `_util.dart`.
---
<details>
Note that many Dart repos have a …
> Fix. typos in _util.dart

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/lib/src/leak_tracking/_primitives/_retaining_path/_connection.dart
- pkgs/leak_tracker/lib/src/leak_tracking/helpers.dart
- pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart
- pkgs/leak_tracker/pubspec.yaml
- pkgs/leak_tracker/test/tests/leak_tracking/retaining_path/_retaining_path_test.dart
- pkgs/leak_tracker_flutter_testing/CHANGELOG.md
- pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart
- pkgs/leak_tracker_flutter_testing/pubspec.yaml
- pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/_retaining_path_test.dart
Contributes to https://github.com/flutter/flutter/issues/135856
> Avoid duplicate leak tracking and remove dependency on logging.

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/pubspec.yaml
Update vm_service to >=11.0.0 <14.0.0
> Prepare for 9.0.12 release

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/lib/src/leak_tracking/primitives/_retaining_path/_connection.dart
- pkgs/leak_tracker/pubspec.yaml
- remove the dependency on package:web_socket_channel
---
<details>
Note that many Dart …
> remove the dependency on package:web_socket_channel

- .github/ISSUE_TEMPLATE/leak_tracker.md
- .github/ISSUE_TEMPLATE/leak_tracker_flutter_testing.md
- .github/ISSUE_TEMPLATE/leak_tracker_testing.md
- .github/ISSUE_TEMPLATE/memory_usage.md
- .github/labeler.yml
- .github/workflows/pull_request_label.yml
- add issue labelers for the pkgs packages
This will normalize what people see when filing issues.
---
<details>
- Changes to packages require [corresponding …
> add issue labelers for the pkgs packages

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/lib/src/leak_tracking/primitives/_print_bytes.dart
- pkgs/leak_tracker/lib/src/leak_tracking/primitives/_retaining_path/_retaining_path.dart
- pkgs/leak_tracker/pubspec.yaml
- remove the dependency on `package:intl`
---
<details>
Note that many Dart repos have …
> remove the dependency on `package:intl`

- doc/BASELINE.md
- doc/DETECT.md
- doc/TROUBLESHOOT.md
- doc/USAGE.md
- pkgs/leak_tracker/lib/src/leak_tracking/primitives/model.dart
- pkgs/leak_tracker/lib/src/usage_tracking/model.dart
- pkgs/leak_tracker/test/test_infra/data/messages.dart
- pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart
- pkgs/memory_usage/lib/src/model.dart
- tool/diagrams.sh
This PR fixes many typo in `leak_tracker`.
---
<details>
Note that many Dart repos have …
> Fix. typos in leak_tracker

- pkgs/leak_tracker/pubspec.yaml
- pkgs/leak_tracker_flutter_testing/CHANGELOG.md
- pkgs/leak_tracker_flutter_testing/lib/src/testing.dart
- pkgs/leak_tracker_flutter_testing/pubspec.yaml
- pkgs/leak_tracker_flutter_testing/test/tests/testing_test.dart
- pkgs/leak_tracker_testing/CHANGELOG.md
- pkgs/leak_tracker_testing/lib/src/leak_testing.dart
- pkgs/leak_tracker_testing/pubspec.yaml
Will be used for the fix https://github.com/flutter/flutter/pull/140521
> Add global enabler to LeakTesting.

- doc/USAGE.md
- pkgs/memory_usage/CHANGELOG.md
- pkgs/memory_usage/pubspec.yaml
Publishing to support this PR: https://github.com/flutter/devtools/pull/6974
> Prepare the package `memory_usage` for publishing.

- pkgs/leak_tracker/lib/src/leak_tracking/helpers.dart
Updated a dead (and very helpful) link to TROUBLESHOOTING.md
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change). …
> Updated URL referencing troubleshooting documentation

- pkgs/leak_tracker/analysis_options.yaml
- pkgs/leak_tracker_flutter_testing/lib/src/testing.dart
This fix will unblock the PR: https://github.com/dart-lang/leak_tracker/pull/248
> Help dependabot to apply new analyzer rules.

- pkgs/leak_tracker/CHANGELOG.md
- pkgs/leak_tracker/pubspec.yaml
Fixes https://github.com/flutter/devtools/issues/6266
> Bump version to make updated readme visible on pub.dev.
