dart-lang/leak_tracker

analysis_options.yaml

The test failures are expected as there is no code yet.

Add lint discarded_futures.

---

README.md

A lot of content is copied from https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/memory/panes/leaks/LEAK_TRACKING.md.
After the PR submission LEAK_TRACKING.md will be deleted.
After tech review, the text should be reviewed with tech writers.

Update documentation for leak tracker.

---

pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/lib/src/leak_tracking/_gc_counter.dart
pkgs/leak_tracker/lib/src/leak_tracking/_object_record.dart
pkgs/leak_tracker/lib/src/leak_tracking/_object_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/leak_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/leak_tracker_model.dart
pkgs/leak_tracker/lib/src/leak_tracking/orchestration.dart
pkgs/leak_tracker/pubspec.yaml
pkgs/leak_tracker/test/debug/leak_tracking/orchestration_test.dart
pkgs/leak_tracker/test/release/leak_tracking/_gc_counter_test.dart
pkgs/leak_tracker/test/release/leak_tracking/_object_tracker_test.dart
pkgs/leak_tracker/test/release/leak_tracking/orchestration_test.dart
pkgs/leak_tracker/test/test_infra/mocks/mock_object_tracker.dart
pkgs/leak_tracker_flutter_test/test/test_infra/mock_object_tracker.dart

1. Enabled customization for gcCountBuffer, so that tests can use value 1 instead of 3.
2. Fine tuned a way to allocate memory in forceGC, to make it working faster
3. Test covered performance of forceGC
Also removed non published versions from changelog.

Improve performance.

---

pkgs/leak_tracker/pubspec.yaml

Without this, it errors on flutter 3.10:
```
Resolving dependencies... (3.3s)
Because every version of xxx from path depends on leak_tracker ^6.0.0 which depends on intl ^0.18.1, every version of
xxx from path requires intl ^0.18.1.
And because every version of xxx from path depends on flutter_localizations from sdk which depends on intl 0.18.0,
xx from path is incompatible with xx from path.
So, because xx depends on both xx from path and xx from path, version solving failed.
```
---
<details>
- Contributions to our repos should …

Make leak_tracker install-able on Flutter stable channel

---

pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/lib/src/leak_tracking/_object_record.dart
pkgs/leak_tracker/pubspec.yaml

The failures affect running application. 
This fix will unblock the PR: https://github.com/flutter/flutter/pull/131998

Stop failing if object is disposed twice.

---

pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/lib/src/leak_tracking/_leak_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/_object_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart
pkgs/leak_tracker/lib/src/shared/_util.dart
pkgs/leak_tracker/pubspec.yaml
pkgs/leak_tracker/test/test_infra/data/dart_classes.dart
pkgs/leak_tracker/test/test_infra/mocks/mock_object_tracker.dart
pkgs/leak_tracker/test/tests/leak_tracking/_object_tracker_test.dart

Instead of using settings for current phase, ObjectTracker should use settings for a phase associated with the tracked object.

Fix issue of using wrong settings for a phase.

---

doc/TROUBLESHOOT.md

Peer PR in Flutter: https://github.com/flutter/flutter/pull/133060

Add instruction to start tracking instances of ChangeNotifier earlier.

---

pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/lib/src/leak_tracking/_object_record_set.dart
pkgs/leak_tracker/lib/src/leak_tracking/_object_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart
pkgs/leak_tracker/pubspec.yaml
pkgs/leak_tracker_flutter_testing/CHANGELOG.md
pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart
pkgs/leak_tracker_flutter_testing/pubspec.yaml
pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/failing_tests/failure_test.dart
pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/failing_tests/flutter_test_config.dart

Contributes to https://github.com/flutter/flutter/issues/135716
This is follow up to fix leak tracker flakiness: https://github.com/flutter/flutter/pull/135394
This PR resolves false negatives, so it is breaking change.
Objects, not disposed by the end of the test, should be marked as leaks, even if they are not GCed yet.
The upgrade to this version should be handled manually, because it may result in some tests failing.

Fix flakiness in detection of notDisposed leaks in tests. 

---

pkgs/leak_tracker/analysis_options.yaml
pkgs/leak_tracker/lib/src/devtools_integration/_protocol.dart
pkgs/leak_tracker/lib/src/devtools_integration/delivery.dart
pkgs/leak_tracker/lib/src/devtools_integration/primitives.dart
pkgs/leak_tracker/lib/src/leak_tracking/_primitives/model.dart
pkgs/leak_tracker/lib/src/shared/shared_model.dart
pkgs/leak_tracker/test/tests/leak_tracking/_leak_checker_test.dart
pkgs/leak_tracker_flutter_testing/lib/src/matchers.dart
pkgs/leak_tracker_flutter_testing/test/tests/end_to_end/baselining_test.dart

Enables the `strict-casts` [analyzer language mode](https://dart.dev/tools/analysis#enabling-additional-type-checks) and fixes the resulting diagnostics.
Works towards the TODO in the `analysis_options.yaml` file of switching to `package:dart_flutter_team_lints` which enables this by default.

Enable and fix strict-casts analyzer mode

---

pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart

This PR fixes typo in `leak_tracking.dart` by changing `leek` to `leak` .
---
<details> …

Fix. typo in leak_tracking.dart

---

examples/autosnapshotting/integration_test/app_test.dart
pkgs/leak_tracker/analysis_options.yaml
pkgs/leak_tracker/lib/src/shared/_util.dart
pkgs/leak_tracker/test/test_infra/data/messages.dart
pkgs/leak_tracker/test/tests/devtools_integration/_envelopes_test.dart
pkgs/leak_tracker/test/tests/leak_tracking/_leak_checker_test.dart
pkgs/leak_tracker/test/tests/leak_tracking/_object_tracker_test.dart
pkgs/leak_tracker/test/tests/leak_tracking/orchestration_test.dart
pkgs/leak_tracker/test/tests/leak_tracking/platform_test.dart
pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart

Enables the [`strict-inference` analysis language mode](https://dart.dev/tools/analysis#enabling-additional-type-checks) to get this repository closer to enabling `package:dart_flutter_team_lints`.

Enable `strict-inference` analysis language mode

---

pkgs/leak_tracker_flutter_testing/CHANGELOG.md
pkgs/leak_tracker_flutter_testing/pubspec.yaml
pkgs/leak_tracker_testing/CHANGELOG.md
pkgs/leak_tracker_testing/lib/src/matchers.dart
pkgs/leak_tracker_testing/pubspec.yaml

Contributes to https://github.com/flutter/flutter/issues/135856

Remove dependency on test.

---

.github/workflows/ci.yaml
examples/autosnapshotting/pubspec.yaml
examples/minimal_flutter/pubspec.yaml
pkgs/leak_tracker/example/pubspec.yaml
pkgs/leak_tracker/pubspec.yaml
pkgs/leak_tracker/pubspec_overrides.yaml
pkgs/leak_tracker_flutter_testing/pubspec.yaml
pkgs/leak_tracker_flutter_testing/pubspec_overrides.yaml
pkgs/leak_tracker_testing/pubspec.yaml
pkgs/leak_tracker_testing/pubspec_overrides.yaml

- use pubspec_overrides.yaml files to specify dependency_overrides
This makes for a cleaner story when we publish these packages.
Related, I would look to break the dependency from `leak_tracker` onto `leak_treacker_testing`. I think we should be able to test `leak_tracker` in isolation from `leak_treacker_testing`, and that will remove a use of dependency overrides in this repo.
---
<details>
- …

use pubspec_overrides.yaml files to specify dependency_overrides

---

CODEOWNERS
README.md
pkgs/leak_tracker_flutter_testing/pubspec.yaml

- reconcile the package descriptions with the readme file
Make the package descriptions in the pubspec files the same as the ones in the readme. Feedback and worksmithing welcome (which description we want to use, ...).
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenan …

reconcile the package descriptions with the readme file

---

pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/analysis_options.yaml
pkgs/leak_tracker/lib/src/leak_tracking/_baseliner.dart
pkgs/leak_tracker/lib/src/leak_tracking/_object_tracker.dart
pkgs/leak_tracker/lib/src/leak_tracking/leak_tracking.dart
pkgs/leak_tracker/lib/src/leak_tracking/primitives/_retaining_path/_retaining_path_isolate.dart
pkgs/leak_tracker/lib/src/leak_tracking/primitives/_retaining_path/_retaining_path_web.dart
pkgs/leak_tracker/lib/src/shared/shared_model.dart
pkgs/leak_tracker/test/tests/leak_tracking/_leak_checker_test.dart
pkgs/leak_tracker_flutter_testing/analysis_options.yaml
pkgs/leak_tracker_testing/analysis_options.yaml

Contributes to https://github.com/flutter/flutter/issues/135856

Separate web implementation for retaining path.

---

pkgs/leak_tracker/lib/src/shared/shared_model.dart

improve the code style and make the code more clear
<details>
Note that many Dart repos …

chore: refactor code style

---

pkgs/leak_tracker_flutter_testing/lib/src/test_widgets.dart

The onLeaks callback did not get invoked.

fix: add missing on leak callback

---

examples/autosnapshotting/pubspec.yaml
examples/leak_tracking/pubspec.yaml
pkgs/leak_tracker/CHANGELOG.md
pkgs/leak_tracker/example/pubspec.yaml
pkgs/leak_tracker/lib/src/leak_tracking/primitives/_retaining_path/_retaining_path_isolate.dart
pkgs/leak_tracker/pubspec.yaml
pkgs/leak_tracker_flutter_testing/CHANGELOG.md
pkgs/leak_tracker_flutter_testing/pubspec.yaml
pkgs/leak_tracker_testing/CHANGELOG.md
pkgs/leak_tracker_testing/pubspec.yaml
pkgs/memory_usage/example/pubspec.yaml
pkgs/memory_usage/pubspec.yaml

Fixes https://github.com/dart-lang/leak_tracker/issues/201 since `package:leak_tracker` is using `dart:developer` APIs only available since Dart 3.2.0.
https://dart-review.googlesource.com/c/sdk/+/346200 adds `Since` information to the relevant APIs and more.

Update Dart SDK constraint to account for used dart:developer APIs

---

.vscode/settings.json
doc/USAGE.md
doc/leak_tracking/DETECT.md

Fixes https://github.com/dart-lang/leak_tracker/issues/215

Note flutter version.

---

doc/leak_tracking/DETECT.md

Motivation: https://github.com/flutter/packages/pull/6210

Instruct not to specify version.

---

.gitignore
doc/leak_tracking/TROUBLESHOOT.md

Fixes https://github.com/dart-lang/leak_tracker/issues/221

Explain exceptions.

---

doc/leak_tracking/DETECT.md

In https://github.com/flutter/packages/pull/7546 I discovered that the signature of `testExecutable` should be 
```dart
Future<void> testExecutable(FutureOr<void> Function() testMain)
```
to be able to compile the tests for the chrome platform.
This PR updates the documentation.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …

Update `testExecutable` signature in documentation

---

doc/leak_tracking/TROUBLESHOOT.md

Changed `addTearDown(aFocusNode.dispose());` to `addTearDown(aFocusNode.dispose);` in docs, since addTearDown accepts a callback.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding …

Fix teardown logic in docs
